### ISSUE TITLE
Why you stop this project 

### ISSUE THREAD

**Issue by geminiyellow** [eiriklv/express-passport-app#10]
@eiriklv 
I think the project is good, why not continue updating it.

**Comment by eiriklv** [comment]
Hi @geminiyellow and thanks :-) The reason why I've deprecated this is that I've moved on to other projects and simply haven't had time to maintain it for a long time. On the way I've built other starter kits/boilerplates that I've used instead. They unfortunately aren't as "complete" as this one from the bottom (i.e - they lack auth and such for instance..). One of the bigger projects we've been working on in Scandinavia Online (an [application assembly platform](https://www.youtube.com/watch?v=Qok_auJbpLM)) is going open source soon - and might fit your need though.

Anyway - If you have ideas and want to update this one I'd be happy to add you as a contributor / give you push rights in the mean time :-)

**Comment by geminiyellow** [comment]
@eiriklv oh, thank you, so, waiting for you new repo.
